### ISSUE TITLE
No plottingscripts.plotting module in PlotOverTime.py

### ISSUE THREAD

**Issue by guoxin1122** [automl/SMAC3_benchmarksuite#1]
Hi,

I was working on the script `PlotOverTime.py` and try to plot the best seen trace over multiple experiments. 

In `PlotOverTime.py`,  there is a statement: 
`from plottingscripts.plotting import plot_methods`, 
but I can't find any module named 'plottingscripts' in SMAC3_benchmarksuite repository. I was wondering if I could get this module to figure out how to plot those best seen trace for various benchmarks.

**Comment by mlindauer** [comment]
Dear Guoxin,

Thanks for your interest in our package. However, please note that this package is only meant for group-internal benchmarking and we do not provide support for this package.

Our official benchmark library is HPOlib (https://github.com/automl/HPOlib2). Please consider to use that one.

To nevertheless answer you question, please look into requirements.txt to find the link to our plottingscript package.

Best regards, 
Marius Lindauer

**Comment by guoxin1122** [comment]
Dear Marius,

I found the link to plottingscripts package in requirements.txt. Thank you so much for your help.

Best regards,
Xin Guo

On 13 Jul 2018, at 08:00, Marius Lindauer <notifications@github.com<mailto:notifications@github.com>> wrote:


Dear Guoxin,

Thanks for your interest in our package. However, please note that this package is only meant for group-internal benchmarking and we do not provide support for this package.

Our official benchmark library is HPOlib (https://github.com/automl/HPOlib2). Please consider to use that one.

To nevertheless answer you question, please look into requirements.txt to find the link to our plottingscript package.

Best regards,
Marius Lindauer
